export const ADD_TO_WANTED_LIST = 'ADD_TO_WANTED_LIST'
export const DELETE_FROM_WANTED_LIST = 'DELETE_FROM_WANTED_LIST'
export const WANTED_LIST_ERROR = 'WANTED_LIST_ERROR'
export const SEARCH_IN_WANTED_LIST = 'SEARCH_IN_WANTED_LIST'