export const GET_PRODUCTS_ALL_REQUEST = 'GET_PRODUCTS_ALL_REQUEST';
export const GET_PRODUCTS_ALL_SUCCESS = 'GET_PRODUCTS_ALL_SUCCESS';
export const GET_PRODUCTS_BY_CATEGORY_REQUEST = 'GET_PRODUCTS_BY_CATEGORY';
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS = 'GET_PRODUCTS_BY_CATEGORY_SUCCESS';
export const GET_POST_BY_ERROR = 'GET_POST_BY_ERROR';
export const GET_CATEGORY = 'GET_CATEGORY';