export const DELETE_FROM_ITEM = 'DELETE_FROM_ITEM';
export const INCRIESE_COUNT = 'INCRIESE_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const BUY_PRODUCTS_FROM_CARD = 'BUY_PRODUCTS_FROM_CARD'
export const ADD_TO_CARD = 'ADD_TO_CARD'
export const SHOW_CARD_LIST_ELEMS = 'SHOW_CARD_LIST_ELEMS'
export const DELETE_FROM_ITEM_LIST = 'DELETE_FROM_ITEM_LIST'
